version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm
      - run: 
          command: npm install
          name: install
      - run: 
          command: npm run build
          name: build







workflows:
  example-workflow:
    jobs:
      - build

          



