version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-ecr: circleci/aws-ecr@9.0
  aws-cli: circleci/aws-cli@4.0

jobs:
  build:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm
      - run: 
          command: npm install
          name: install
      - run: 
          command: npm run build
          name: build

workflows:
  build-and-push:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          account_id: AWS_ACCOUNT_ID
          auth:
            - aws-cli/setup:  
                role_arn: $AWS_ARN
          context: CircleCI_OIDC_Token
          platform: linux/amd64
          dockerfile: Dockerfile
          path: .
          repo: frontend
          tag: latest
          requires:
            - build




          



