version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-ecr: circleci/aws-ecr@9.0
  aws-cli: circleci/aws-cli@4.0

jobs:
  build:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm
      - run: 
          command: npm install
          name: install
      - run: 
          command: npm run build
          name: build

workflows:
  build-and-push:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:  
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
                region: AWS_REGION
          context: CircleCI_OIDC_Token
          dockerfile: Dockerfile
          path: .
          repo: frontend
          tag: latest
          requires:
            - build




          



